commiting forked branch
vle-forge/irritator pull request #37
Opened 2021-06-07 16:51 UTC by ovese

This is the pull request for Gauthier on updated SEIR for irritator

2021-06-07 16:58 UTC, ovese commented
The branch seirdeux has no conflicts. learnt a thing about pull requests from this task.

2021-06-08 08:00 UTC, quesnel requested changes
Please, can you change the commit name? For example:
`gui: add QSS1 Seir model`

2021-06-08 08:01 UTC, quesnel commented on app/gui/node-editor.cpp
> +            /*
Please, use `clang-format` (available with Visual Studio) to format C++ code.

2021-06-08 08:09 UTC, quesnel reviewed
I prefer two patchs. First for examples.hpp, second for the gui.

2021-06-08 08:09 UTC, quesnel commented on lib/include/irritator/examples.hpp
> +        bool success = sim.can_alloc<abstract_wsum<QssLevel, 2>>(2) &&
Please, this is an old API. Can you update your repository and use:
`sim.models.can_alloc(10)`

2021-06-08 08:09 UTC, quesnel commented on lib/include/irritator/examples.hpp
> +            sim.can_connect(12);//pour le seir_linear qu'est-ce que le nombre de connection 12,
The function `sim.can_connect(12)` checks if the `irt::simulation` object can allocate `12` new connections between models. In irritator simulation kernel (`irritator/core.hpp`), all objects are pre-allocated. No memory allocation is allowed during simulation.

2021-06-08 08:09 UTC, quesnel commented on lib/include/irritator/examples.hpp
> +        //static_assert(1 <= QssLevel && QssLevel <= 3, "Only for Qss1, 2 and 3");
You can remove this line.

2021-06-08 08:09 UTC, quesnel commented on lib/include/irritator/examples.hpp
> +            sim.can_connect(32);//pour le seir_non_linear qu'est-ce que le nombre de connection 32?
Replace `32` with the correct number of `sim.connect(...)` call and remove the comment.

2021-06-08 08:09 UTC, quesnel commented on app/gui/node-editor.cpp
> +            /*
Please, use clang-format (available with Visual Studio) to format C++ code.

2021-06-09 15:24 UTC, quesnel commented
Some remarks:
- There is many error in the file. For example, `sim.models.can_connect()` can not build. There is no `can_connect()` function in `irt::data_array` class. Prefer the use of  `sim.can_alloc()` and `sim.can_connect()`.
- Use `clang-format` (see: https://devblogs.microsoft.com/cppblog/clangformat-support-in-visual-studio-2017-15-7-preview-1/  for Visual Studio 2019).
- I prefer the rebase instead of merge in git. Use `git rebase origin/master` to merge your code.

2021-06-14 12:37 UTC, quesnel commented on lib/include/irritator/examples.hpp
> +    // bool success = sim.can_alloc<abstract_wsum<QssLevel, 2>>(2) &&
You can remove these comments.

2021-06-14 12:38 UTC, quesnel commented on lib/include/irritator/examples.hpp
> +    //                sim.can_alloc<abstract_multiplier<QssLevel>>(1) &&
You can remove these comments.

2021-06-14 12:38 UTC, quesnel commented on lib/include/irritator/examples.hpp
> +    // bool success = sim.can_alloc<abstract_wsum<QssLevel, 2>>(1) &&
You can remove these comments.

2021-06-14 12:38 UTC, quesnel commented on lib/include/irritator/examples.hpp
> +    // bool success = sim.can_alloc<constant>(3) &&
You can remove these comments.

2021-06-14 12:38 UTC, quesnel commented on lib/include/irritator/examples.hpp
> +    //                sim.can_alloc<abstract_integrator<QssLevel>>(1) &&
You can remove these comments.

2021-06-14 12:38 UTC, quesnel commented on lib/include/irritator/examples.hpp
> +    //                sim.can_alloc<abstract_wsum<QssLevel, 2>>(3) &&
You can remove these comments.

2021-06-14 12:38 UTC, quesnel commented on lib/include/irritator/examples.hpp
> +    // bool success = sim.can_alloc<abstract_wsum<QssLevel, 3>>(1) &&
You can remove these comments.

2021-06-14 12:38 UTC, quesnel commented on lib/include/irritator/examples.hpp
> +    // bool success = sim.can_alloc<abstract_wsum<QssLevel, 2>>(1) &&
You can remove these comments.

2021-06-14 12:38 UTC, quesnel commented on lib/include/irritator/examples.hpp
> +        // bool success = sim.can_alloc<abstract_wsum<QssLevel, 2>>(2) &&
You can remove these comments.

2021-06-14 12:38 UTC, quesnel commented on lib/include/irritator/examples.hpp
> +        // bool success = sim.can_alloc<abstract_wsum<QssLevel, 2>>(2) &&
You can remove these comments.

2021-06-14 12:40 UTC, quesnel requested changes
It's almost good. Just remove all comments and provides a better commit message. For examples:
examples: add QSS1 SEIR model

2021-06-14 12:42 UTC, quesnel commented
There is a conflict in the file `app/gui/node-editor.cpp`. You need to get the latest version with `git rebase origin/master` for example.

2021-06-16 14:35 UTC, quesnel commented
I close this pull request: #52 replace #37.

2021-06-16 14:35 UTC, closed without merging