model: filter threshold parameters added
vle-forge/irritator pull request #69
Opened 2021-07-27 23:22 UTC by ovese

Adding parameters to filter model in core.cpp. Threshold parameters added and undergoing improvements

2021-07-28 08:17 UTC, quesnel requested changes
All changes in switch must be merge with the previous patch to fix all warnings in North gcc and msvc.

2021-07-28 08:17 UTC, quesnel commented on lib/include/irritator/core.hpp
> +               sizeof(filter),
This change must be merge with the previous patch.

2021-07-28 08:17 UTC, quesnel commented on lib/include/irritator/core.hpp
> +    if constexpr (std::is_same_v<Dynamics, filter>)
This change must be merge with the previous patch.

2021-07-28 08:17 UTC, quesnel commented on lib/include/irritator/core.hpp
> +        case dynamics_type::filter:
This change must be merge with the previous patch.

2021-07-28 08:17 UTC, quesnel commented on lib/include/irritator/core.hpp
> +        case dynamics_type::filter:
This change must be merge with the previous patch.

2021-07-28 08:17 UTC, quesnel commented on lib/include/irritator/core.hpp
> +        case dynamics_type::filter:
This change must be merge with the previous patch.

2021-07-28 10:45 UTC, ovese commented
I have made the merger of the commits. could you let me know if its ok now

2021-07-29 14:51 UTC, quesnel commented
I am merging the patch myself. I delete the unnecessary parts. Thank you.

2021-07-29 14:51 UTC, closed without merging